lambda_aws_access_key_id     = "ASIA2VKUD45EB37AY27P"
lambda_aws_secret_access_key = "yuSGaJRovYIHpxqhOZd/gwM8HFjCs14Th0GkX4en"
bucket_name                  = "fiapx-bucket-upload"
api_gateway_id               = "l8hetzgmq6"
api_gateway_root_resource_id = "puhl08zele"
cognito_user_pool_arn        = "arn:aws:cognito-idp:us-east-1:733005211464:userpool/us-east-1_XPCibTOvX"
cognito_user_pool_id         = "us-east-1_XPCibTOvX"
cognito_app_client_id        = "1vq77caiob35e2an3ssvg60ru2"