name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: 'us-east-1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: './infra'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Zip Lambda Function
        run: zip -r ../../lambda_function.zip .
        working-directory: app/src

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Export AWS credentials
        run: |
          echo "Exporting AWS credentials for Terraform..."
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> $GITHUB_ENV
      
      - name: Check environment variables
        run: |
          echo "aws_access_key_id = $aws_access_key_id"
          echo "aws_secret_access_key = $aws_secret_access_key"
          echo "aws_session_token = $aws_session_token"   

      - name: Terraform Init
        run: terraform init

      - name: Terraform Fmt
        run: terraform fmt -check -no-color  

      - name: Terraform Validate
        run: terraform validate -no-color  

      - name: Terraform Plan
        run: terraform plan -out terraform.plan

      - name: Terraform Apply 
        run: terraform apply -auto-approve